// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationFooter: typeof import('./src/components/site/ApplicationFooter.vue')['default']
    ApplicationHeader: typeof import('./src/components/site/ApplicationHeader.vue')['default']
    ApplicationSidebar: typeof import('./src/components/site/ApplicationSidebar.vue')['default']
    CellView: typeof import('./src/components/layout-designer/CellView.vue')['default']
    ConfirmationDialog: typeof import('./src/components/site/ConfirmationDialog.vue')['default']
    InformationDialog: typeof import('./src/components/site/InformationDialog.vue')['default']
    LayoutGrid: typeof import('./src/components/layout-designer/LayoutGrid.vue')['default']
    ModuleList: typeof import('./src/components/layout-designer/ModuleList.vue')['default']
    MutateDialog: typeof import('./src/components/site/MutateDialog.vue')['default']
    RecordPager: typeof import('./src/components/site/RecordPager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleSwitch: typeof import('./src/components/site/ToggleSwitch.vue')['default']
    ToolboxGrid: typeof import('./src/components/layout-designer/ToolboxGrid.vue')['default']
    ToolDefinitionView: typeof import('./src/components/layout-designer/ToolDefinitionView.vue')['default']
  }
}

export {}
